### ISSUE TITLE
Add ability to update local clones?

### ISSUE THREAD

**Issue by geerlingguy** [cooperspencer/gickup#1]
This is great, pretty much exactly what I was looking to do, but one thing I would also hope to be able to do is something like:

```
./gickup --update path-to-config.yml
```

And in that case, it would:

1. Get the list of repos from GitHub/Gitea/etc.
2. For each repo:
  1. Check if it is already cloned locally.
  2. If not: clone it.
  3. If so: go into the clone, and run `git fetch --all` and `git pull --all`

The reason I'd like this is so I can save on bandwidth in terms of having 300+ repos (some of them dozens of MB), and I don't want to re-clone all of them nightly :)

**Comment by cooperspencer** [comment]
It already does that.
```go
		if _, err := os.Stat(repo.Name); os.IsNotExist(err) {
			fmt.Printf("cloning %s\n", green(repo.Name))
			err := git.Clone(repo.Url, repo.Name, git.CloneOptions{Quiet: false, Timeout: 5 * time.Minute})
			if err != nil {
				if x == tries {
					panic(err)
				} else {
					fmt.Printf("retry %s from %s\n", red(x), red(tries))
					time.Sleep(5 * time.Second)
					continue
				}
			}
		} else {
			fmt.Printf("pulling %s\n", green(repo.Name))
			r, err := git.Open(repo.Name)
			if err != nil {
				if x == tries {
					panic(err)
				} else {
					os.RemoveAll(repo.Name)
					fmt.Printf("retry %s from %s\n", red(x), red(tries))
					time.Sleep(5 * time.Second)
					continue
				}
			}
			err = r.Pull(git.PullOptions{All: true, Branch: repo.Defaultbranch})
			if err != nil {
				if x == tries {
					panic(err)
				} else {
					os.RemoveAll(repo.Name)
					fmt.Printf("retry %s from %s\n", red(x), red(tries))
					time.Sleep(5 * time.Second)
					continue
				}
			}
		}
```
it checks if the directory already exists, if not, it clones it, otherwise it just does a pull.

**Comment by cooperspencer** [comment]
I just added `fetch` to the local checkout.
