### ISSUE TITLE
Cannot mirror private gitlab repository to custom gitlab-ce instance

### ISSUE THREAD

**Issue by GTVolk** [cooperspencer/gickup#106]
Hello everyone! Thank you for such wonderful tool for backuping my repos, it is awesome! But i'am have issue with mirroring my private repos from gitlab.com to selfhosted gitlab-ce instance. I use token authentication, it grabs all my private repos successfully, but, when it trying to mirror i get an error saying: 

`<LOGDATE> FTL POST http://<SELFHOSTEDURL>/api/v4/projects: 422 {message: https://<TOKEN>@gitlab.com/<USERNAME>/<REPO>.git is not a valid HTTP Git repository} stage=gitlab url=<SELFHOSTEDURL>`

Where redacted `<LOGDATE>` - log date, `<SELFHOSTEDURL>` - my selfhosted gitlab-ce instance url, `<TOKEN>` - private token for gitlab.com, `<USERNAME>` - my gitlab.com username, `<REPO>` - my gitlab.com repo name.

Can you do something with this issue and fix it, please? :)

**Comment by cooperspencer** [comment]
Hi,
asfaik Gitlab CE doesn't support mirroring.
If you want to "mirror" your changes, you could use [charly](https://github.com/cooperspencer/charly) for that.
It just checks for changes in your repository and runs an action as soon a new commit is detected.
This config can be used for your use case: https://github.com/cooperspencer/charly/issues/1#issuecomment-1063354320

**Comment by GTVolk** [comment]
Thanks, I'll try this too, i doesn't know about it! I'm a bit wrong in description what I'm doing, I just want to import all repositories from gitlab.com to custom gitlab-ce instance, not necessarily mirror them. But I can't do that either, I get exactly this error. :(
