### ISSUE TITLE
Gitea Destination: Token missing on `/api/v1/version` call

### ISSUE THREAD

**Issue by miped** [cooperspencer/gickup#120]
If you enable `REQUIRE_SIGNIN_VIEW` in your gitea instance, then _everything_ requires signin, even `/api/v1/version`. Gickup does not pass the token to this api endpoint, so it gets a 403 forbidden and stops.

**Comment by cooperspencer** [comment]
should be fixed with the latest commit. can you compile it and try if it solves your issue?

**Comment by cooperspencer** [comment]
fixed in the latest release [v0.10.7](https://github.com/cooperspencer/gickup/releases/tag/v0.10.7)

**Comment by miped** [comment]
Same with this, worked perfectly 👍 Thank you for the quick resolution.
