### ISSUE TITLE
Gitea Destination: Support for creating organizations on demand

### ISSUE THREAD

**Issue by miped** [cooperspencer/gickup#121]
I currently have a setup where i explicitly list the organizations that i want synced, because i need to create them in gitea before i can sync them. I was wondering if it would be possible to have gickup create the necessary organizations on demand?

At least for my use case, there is no risk of collisions, since the local gitea instance is purely for backup purposes.

**Comment by cooperspencer** [comment]
if you compile the latest version, try to add `createorg: true` to your destination config for gitea. it should be able to create organizations if needed.

**Comment by cooperspencer** [comment]
fixed in the latest release [v0.10.7](https://github.com/cooperspencer/gickup/releases/tag/v0.10.7)

**Comment by miped** [comment]
Finally got around to testing this. Worked like a charm 👍
