### ISSUE TITLE
Sourcehut support

### ISSUE THREAD

**Issue by samhh** [cooperspencer/gickup#122]
It's missing! :slightly_smiling_face:

**Comment by cooperspencer** [comment]
I don't have a sourcehut account but I'll look into it

**Comment by cooperspencer** [comment]
@samhh I am currently implementing sourcehut to gickup. Do you by chance know a user with more than 50 repos there?

**Comment by cooperspencer** [comment]
Thanks for that.
It should be possible to backup your sourcehut repos.
Can you please test if it works for you as expected? Just compile [sourcehut branch](https://github.com/cooperspencer/gickup/tree/sourcehut), add your sourcehut config to the configfile and give it a go.

I tested it with sircmpwns' and your account and it worked fine for me.

**Comment by cooperspencer** [comment]
I just published a new release [v0.10.7](https://github.com/cooperspencer/gickup/releases/tag/v0.10.7).
The sourcehut functionality is added there
