### ISSUE TITLE
Ability to have local path be time based

### ISSUE THREAD

**Issue by jclusso** [cooperspencer/gickup#129]
I'm confused how this is really considered a backup without this functionality. If any repository is compromised and receives a bad commit of some sort, the backup will reflect that rendering it useless. It would be nice if `path` was evaluated so you could include the date in it some how.

**Comment by cooperspencer** [comment]
What exactly do you mean by that? Like cloning the repository and adding the clone date and time to the path? `/clone-path/repo-$DATE`

**Comment by cooperspencer** [comment]
Or creating a zip file with the date after the cloning is done

**Comment by jclusso** [comment]
Both would be great! If path was evaluated one could do anything they want regarding date and time control. 

Having a compressed or zip option would be awesome for storage savings too if you could have it compress each repo. Having each one separate would be ideal vs one big zip. 

We were just going to dump everything in a folder that's mounted to AWS S3 but right now we'd have to do some post processing in a separate script or something and can't use your built in cron .

**Comment by jclusso** [comment]
Ex: /backup/2023/01/06/github.com/username/repo.zip

**Comment by cooperspencer** [comment]
I really like this idea. I'll look into it

**Comment by cooperspencer** [comment]
I just added the function to add the date to the backup path.
I used the same structure as in your example.
it's in the [time_to_path_and_zip](https://github.com/cooperspencer/gickup/tree/time_to_path_and_zip) branch, if you want to try it out.

**Comment by jclusso** [comment]
Awesome! Building from source now!

**Comment by jclusso** [comment]
@cooperspencer I think that does the trick. I'm debating if we should add the time, but I'm not sure if that's overkill on this. I just tried it out and I can't decide. 

Having daily backups probably suffices for my usecase, but I don't know about others.  I think that if time was included it would be best to have `date` like you have and `time` as another option.  If you don't think it's necessary I completely understand! This change is huge as it is. I would've made a PR myself, but I don't really know any Go and wasn't sure where to start looking here.

**Comment by cooperspencer** [comment]
just pushed the zip functionality. regarding date, I am thinking about adding date to the zip-file and maybe also add a keep parameter to delete old backups.

**Comment by jclusso** [comment]
@cooperspencer I'm indifferent as long as the functionality is there. ZHow would the keep parameter work? I was just going to rely on an S3 policy to delete old files older than a certain date, but if you did something that was like keep the last X number backups that would simplify things!

**Comment by cooperspencer** [comment]
That's what I planned. It would be like keep X backups

**Comment by cooperspencer** [comment]
Awesome! I'll add the `keep` parameter tomorrow. I'll keep you posted

**Comment by cooperspencer** [comment]
@jclusso Just implemented the `keep` parameter. It just keeps X backups

**Comment by cooperspencer** [comment]
I might remove the `date` parameter again. I think it is sufficient to have the `keep` option because it adds the unix timestamp to the backup path.

**Comment by jclusso** [comment]
What about something like this with keep enabled and no date option. 

`/backup-path/github.com/[repo-name]/[timestamp].git`

**Comment by cooperspencer** [comment]
This sounds good

**Comment by cooperspencer** [comment]
@jclusso just removed the `date` parameter and implemented that `keep` creates a directory/zip file with the timestamp as name.

**Comment by jclusso** [comment]
@cooperspencer nice! Appears to work as expected!

**Comment by cooperspencer** [comment]
released with [v0.10.10](https://github.com/cooperspencer/gickup/releases/tag/v0.10.10)
