### ISSUE TITLE
Automatically accept hostkey somehow on first run?

### ISSUE THREAD

**Issue by geerlingguy** [cooperspencer/gickup#13]
On the first run of this script, on a server where I don't log into other things via SSH (and haven't cloned anything from GitHub previously), I got the following error after a few tries cloning a repo:

```
5:07PM INF cloning 3d-printing path=/Volumes/Git-Backups stage=locally
5:07PM PNC unable to find any valid known_hosts file, set SSH_KNOWN_HOSTS env variable path=/Volumes/Git-Backups stage=locally
panic: unable to find any valid known_hosts file, set SSH_KNOWN_HOSTS env variable

goroutine 1 [running]:
github.com/rs/zerolog.(*Logger).Panic.func1({0x40004aefa0, 0x4b})
	/home/runner/go/pkg/mod/github.com/rs/zerolog@v1.25.0/log.go:359 +0x48
github.com/rs/zerolog.(*Event).msg(0x40000b1b60, {0x40004aefa0, 0x4b})
	/home/runner/go/pkg/mod/github.com/rs/zerolog@v1.25.0/event.go:149 +0x2b8
github.com/rs/zerolog.(*Event).Msg(...)
	/home/runner/go/pkg/mod/github.com/rs/zerolog@v1.25.0/event.go:108
main.Locally({{0x4000376770, 0xb}, {0x40004be150, 0x2e}, {0x40004be120, 0x2a}, {0x40000c72c0, 0x28}, {0x400037682a, 0x6}, ...}, ...)
	/home/runner/work/gickup/gickup/main.go:106 +0x66c
main.Backup({0x4000600000, 0x167, 0x216}, 0x400022e1e0)
	/home/runner/work/gickup/gickup/main.go:246 +0x22c
main.main()
	/home/runner/work/gickup/gickup/main.go:462 +0x34c
```

I had to run `ssh-keyscan github.com >> ~/.ssh/known_hosts` to generate that file, then after re-running `gickup`, it seemed to work correctly.

It would be nice if there was an easier way to either automatically accept the hostkey to generate that known_hosts file, or maybe offer some easier advice besides the built-in panic message.

Not a huge deal, and at least now this issue exists so hopefully future Google searches can find a quick fix.

**Comment by cooperspencer** [comment]
I'll take a look at that. There must be a way to implement that in go.

**Comment by cooperspencer** [comment]
Good morning,
I implemented goph, with that I can check for ssh-keys in the known_hosts file and add them to it if needed.

**Comment by geerlingguy** [comment]
Excellent, thanks!
