### ISSUE TITLE
Backup/Mirror based on filter results

### ISSUE THREAD

**Issue by ShalokShalom** [cooperspencer/gickup#136]
Hi 😊

I am inclined to mirror A LOT of repositories to my instance of DevOne. 

I know, there is no backend for it, and I am aware, that you write a binding to Java, that makes it possible. 

In case you get bored then: I like to backup basically all repositories of a certain language (F#), that would require the app to be aware of Github's filter/search API..

Another point that might be interesting, is to sort out repositories with less than 10 stars, archived ones, and/or those who had not seen an update for 10 years. ⏰ 

The filtering mechanism is obviously a bonus, it would significantly reduce the amount of repos to be cloned. 😊 

I can also do it by hand. 
Just think this could be a neat feature. 👍🏻

Have a good day!

**Comment by cooperspencer** [comment]
Hi fellow Viennese,

I just had a look at your account and you really have a lot of starred repositories.

I will have a look at the APIs of Github and co. and see what I can do.

I'll keep you posted.

**Comment by cooperspencer** [comment]
I had a look at the different APIs:
Github:
- Stars - ok
- Language - ok
- Last updated - ok

Gitea/Forgejo:
- Stars - ok
- Language - ok
- Last updated - ok

Gogs:
- Stars - ok
- Language - nope
- Last updated - ok

Gitlab:
- Stars - ok
- Language - ok
- Last updated - ok

Sourcehut:
- Stars - nope
- Language - nope
- Last updated - ok

OneDev:
- Stars - nope
- Language - nope (opened an issue for that one)
- Last updated - ok

Bitbucket:
- Stars - nope
- Language - nope
- Last updated - ok

regarding the requirement `not updated in the last 10 years`. Do you want this feature only in the default branch or should it apply to all branches?

**Comment by ShalokShalom** [comment]
That's wonderful

I mainly want that to sort out the stuff that's unmaintained for years.

Since its unlikely that the main branch has no commit for years, and there is development going on in a subbranch, I think that's not needed. 

Thanks a lot

**Comment by jholdstock** [comment]
Hi @cooperspencer. Thanks for your great work on gickup! I run it daily on my server to backup my projects from GitHub to local storage.

For me, the most important of the filters listed by @ShalokShalom would be archived projects. I actually run [my own fork](https://github.com/jholdstock/gickup/commit/70f4f71254f4bde744003d6d659e25482a55f753) with that filter hacked in.

I would love to see first class support for this!

**Comment by cooperspencer** [comment]
Hi @jholdstock,
I just saw your message. Awesome idea, I included this in the latest changes of the [filter](https://github.com/cooperspencer/gickup/tree/filter) branch. So if anyone wants to test it, the config looks something like this:
```yaml
source:
  github:
    - user: cooperspencer
      filter:
        lastactivity: 1y
        stars: 700
        languages:
          - dockerfile
          - go
        excludearchived: true
destination:
  local:
    - path: backup
      structured: true
```

I will include these changes, as far as possible, for the other hosters too.

**Comment by cooperspencer** [comment]
In my tests everything went smoothly, so I merged it into `main`.
Feel free to test it.

**Comment by cooperspencer** [comment]
@ShalokShalom 
I have just added a mirroring option for OneDev to the `main` branch.
