### ISSUE TITLE
Backup GitHub Issues

### ISSUE THREAD

**Issue by stefnotch** [cooperspencer/gickup#157]
I've read through the documentation, but I can't find anything about "backing up GitHub/GitLab issues". 

Being able to make a local, offline backup of the issue tracker is pretty important for me, as otherwise, GitHub issues are only available on their website.

If this is supported, I'd love to see it documented and advertised.
If not, I'd love to see this become supported.

**Comment by cooperspencer** [comment]
Gickup currently only backs up repositories and wikis. I need to investigate how much work it would take to back up issues as well.

**Comment by stefnotch** [comment]
Thanks for the answer. Part of why I think it's important to back up GitHub issues is the youtube-dl fiasco, where the repository was locked. During that time, none of the information that was stored in the GitHub issues was accessible[1], which was rather troubling. 

[1] Well, except through the internet archive.

**Comment by cooperspencer** [comment]
Fair point. I'll look into it and try to come up with something

**Comment by cooperspencer** [comment]
I began investigating it, and without an API token, you quickly encounter the API limit. The best option would be to enable this only when the token is in use.

**Comment by cooperspencer** [comment]
I started working on it. For now it works with a local backup of the issues from github.
https://github.com/cooperspencer/gickup/pull/185

**Comment by cooperspencer** [comment]
Just merged it to `main`. I will push a new release with those changes today or tomorrow.

**Comment by cooperspencer** [comment]
just pushed a new release including the backups for issues
