### ISSUE TITLE
LFS support

### ISSUE THREAD

**Issue by miconx** [cooperspencer/gickup#158]
does gickup support LFS files wihtin repositories? 
i used gickup to backup a repo with lfs files but the files did not appear in the destination repo
for it seems that they are ignored completely
thanks for any hints

**Comment by cooperspencer** [comment]
I didn't have LFS in mind when I wrote gickup. Right now it doesn't support it, I'll take a look at go-git and figure out how to enable it.

**Comment by cooperspencer** [comment]
`go-git` doesn't support lfs. I could use the `git-lfs` command until `go-git` supports it or until another module becomes available.

**Comment by miconx** [comment]
ok thank you - btw thans for releasing gickup its super useful ;-)

**Comment by cooperspencer** [comment]
You are very welcome, always glad when someone uses my tools :smile: 
I created a new branch called `git-lfs`, can you compile and test it to see if it does what you need?
The config for `lfs` is like this:
```yaml
destination:
  local:
    - path: ~/backup
      lfs: true
```

**Comment by cooperspencer** [comment]
feature is now included in the `main` branch. If you run into any problems, feel free to reopen the issue.
