### ISSUE TITLE
GitHub destination support

### ISSUE THREAD

**Issue by adamcstephens** [cooperspencer/gickup#163]
I’d love to be able to use gickup copy from my local gitea/forgejo instance to github.

**Comment by cooperspencer** [comment]
I'm currently working on adding this feature. The challenge I'm facing is that Github doesn't have the same mirror feature as gogs, gitea, or forgejo. This makes the implementation a bit trickier. I'll let you know how it goes.

**Comment by cooperspencer** [comment]
Hi,

I have just added a mirroring option for Github to the `main branch. Could you please test and confirm if it functions as you intended?

**Comment by adamcstephens** [comment]
This works as I'd expect, but does show an error when the destination is already up to date

```
2023-08-15T15:35:23-04:00 ERR already up-to-date stage=github url=https://codeberg.org/adamcstephens/nix-sandbox.git
```

**Comment by cooperspencer** [comment]
Thanks a lot for testing it. I'll fix that issue tomorrow. 'go-git' returns an error if anything is already up to date.

**Comment by adamcstephens** [comment]
Do the other destinations that natively support mirroring handle all branches? I just realized this only syncs the main branch.

**Comment by cooperspencer** [comment]
the current `main` branch should push all branches and tags.

> Do the other destinations that natively support mirroring handle all branches? I just realized this only syncs the main branch.

Yes, gitea/gogs/forgejo mirror all branches and tags by default.

**Comment by adamcstephens** [comment]
Mirroring all the branches is now working for the GitHub destination.

**Comment by cooperspencer** [comment]
i pushed [v0.10.18](https://github.com/cooperspencer/gickup/releases/tag/v0.10.18) and those features are now included.
