### ISSUE TITLE
Gitea destination mirror internal 

### ISSUE THREAD

**Issue by defyjoy** [cooperspencer/gickup#173]
As we can see gitea has a interval for mirroring the remote repo from source . That is an inbuilt feature , so technically we do not have to run gickup everytime. It runs only when we want to. But once mirrored , gitea can take over it and on specific intervals to keep pulling changes . 

Can we have this config added in gitea destination configuration as a new feature request ?

![image](https://github.com/cooperspencer/gickup/assets/1047068/647025c5-06ea-466e-9b34-f17f9067f380)

**Comment by cooperspencer** [comment]
I'll check the gitea sdk and get back to you.

**Comment by cooperspencer** [comment]
I added the feature in https://github.com/cooperspencer/gickup/pull/174. I will merge it a bit later and create a new release.

**Comment by cooperspencer** [comment]
It's now in `main`, can you test if it does what you want?

**Comment by defyjoy** [comment]
So there is one issue I am facing for this . If the repo is mirrored once into gitea with config `mirrorinterval: 2h0m0s` and I change to `mirrorinterval:1h0m0s`.Now if I run `./gickup conf.yaml` for the 2nd time. The change does not reflect . Is there any way we can solve this ?

**Comment by cooperspencer** [comment]
I'll need to add that to the code. Shouldn't be a big issue. I'll let you know when it's done.

**Comment by cooperspencer** [comment]
I just merged into into `main`. Can you re-test it?

**Comment by defyjoy** [comment]
Perfect ! it working as expected

**Comment by defyjoy** [comment]
Could you please release this as docker image ?

**Comment by cooperspencer** [comment]
Sure, I'll release it in an hour or two. I'll notify you here when it's done.

**Comment by cooperspencer** [comment]
Release [v0.10.21](https://github.com/cooperspencer/gickup/releases/tag/v0.10.21) is out. It will take a bit for the containers and binaries to be built.

**Comment by defyjoy** [comment]
Thanks a ton . Closing this issue and again thanks for the fantastic support

**Comment by defyjoy** [comment]
@cooperspencer This is not yet documented . Could you please document this

**Comment by cooperspencer** [comment]
where did I forget to add it? It's in the documentation:
https://cooperspencer.github.io/gickup-documentation/docs/configuration/destination/gitea/
and it the example configuration:
https://github.com/cooperspencer/gickup/blob/main/conf.example.yml#L207
