### ISSUE TITLE
Ubuntu container image doesn't seem to be based on Ubuntu

### ISSUE THREAD

**Issue by drweissbrot** [cooperspencer/gickup#181]
I encountered this while trying to run a shell script in the container to send a heartbeat HTTP request. (I've since found out that Gickup can do that by itself, neat! :D)

Specifically, I tried running this command, just to get a shell to play around:
```sh
docker run --entrypoint sh --rm -it buddyspencer/gickup:ubuntu-0.10.21
```
which failed with this output, saying that it couldn't find `sh`:
```sh
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "sh": executable file not found in $PATH: unknown.
```

For comparison, running `docker run --entrypoint sh --rm -it ubuntu:latest` (the [Dockerfile](https://github.com/cooperspencer/gickup/blob/633483a2753e99fa930a046344313f0f6165fd45/Dockerfile.ubuntu) doesn't seem to specify a version) puts me onto a shell just fine.

I then started a container each using the ubuntu and the "normal" image and exported their file systems:
```sh
docker run --name gickup-ubuntu-export buddyspencer/gickup:ubuntu-0.10.21
docker export gickup-ubuntu-export > ubuntu.tar

docker run --name gickup-scratch-export buddyspencer/gickup:0.10.21
docker export gickup-scratch-export > scratch.tar
```

Inspecting these, they're both identical. Github won't let me upload the TARs unfortunately, but even the content checksums are the same.  
From my understanding, the Ubuntu image should include a lot more files than the scratch-based one.

It looks to me like both images are actually the same? Or maybe I'm just doing it wrong? :D

**Comment by cooperspencer** [comment]
I think I made a mistake somewhere in the pipelines. I'll check it out tomorrow or on Monday. I am currently on vacation without my laptop. I'll keep you posted.
But thanks for noticing this issue.

**Comment by cooperspencer** [comment]
Thanks a lot; you were absolutely right. I forgot to add the correct Dockerfile in the build step for the Ubuntu container. I'll push a new release shortly, and the Ubuntu container should be fine then.

**Comment by cooperspencer** [comment]
I just tested it and it seems to be ok now.
