### ISSUE TITLE
Implement `--version`

### ISSUE THREAD

**Issue by geerlingguy** [cooperspencer/gickup#19]
One last thing that would be handy, since there are now releases and official cool stuff like that—it would be nice if the release could somehow also add in the version to the binary, and a run of `gickup --version` could output it.

And if not an official tag, it could be the git SHA, or just `unknown`.

**Comment by cooperspencer** [comment]
I implemented the version tag for now. I need to look a bit deeper into how to switch between different version strings.
When I figure it out, I'll add it.

**Comment by ryanfaerman** [comment]
One thing I like doing, when setting version numbers, is to use some linker flags to define a variable.

For example, I may define something like:

```go
var Version = "unknown"
```

and then define that in my pipeline with 

```shell
$ go build -X "github.com/ryanfaerman/mypackage/main.Version=9.3.1"
```

If you get slightly clever you can then set that value from git or anywhere else you like.

I do this frequently enough that I made a small package that has my standard implementation of version info https://github.com/ryanfaerman/version.

**Comment by cooperspencer** [comment]
Thanks, that is actually genius 😄

**Comment by cooperspencer** [comment]
this is included in the latest main branch. Thanks @ryanfaerman
