### ISSUE TITLE
Gitea SDK have the repo description length limit of 255

### ISSUE THREAD

**Issue by WantToLearnJapanese** [cooperspencer/gickup#194]
AFAIK, the limit is relieved from the newer version, however gitea-sdk, which GickUP depends on have the limitation check.
So the description of the source repo exceeds 255 chars, it fails to clone.

https://gitea.com/gitea/go-sdk/src/commit/bde56fb9bb02969b0421e7b6d85256312b4a6077/gitea/repo_migrate.go#L65

**Comment by cooperspencer** [comment]
Seems to be correct. Just checked the Gitea repository and they increased it last year to 2048 characters. I guess they forgot to do that in the SDK.

Here the corresponding commit:
https://github.com/go-gitea/gitea/commit/8351172b6e5221290dc5b2c81e159e2eec0b43c8

**Comment by cooperspencer** [comment]
I opened a PR on gitea-sdk for that issue:
https://gitea.com/gitea/go-sdk/pulls/645

Thanks for bringing it to my attention

**Comment by cooperspencer** [comment]
They merged my PR and I'll update the Gitea sdk as soon as they create a new release.

**Comment by WantToLearnJapanese** [comment]
They finally released the fix!
Thank you for your hard work.

**Comment by cooperspencer** [comment]
You are welcome.
I updated the modules. If you use docker you can use `buddyspencer/gickup:dev` or `buddyspencer/gickup:ubuntu-dev`. I will create a new release soon, I just have to wait for another issue to be resolved.

**Comment by cooperspencer** [comment]
I just pushed a new release. It should be available soon
