### ISSUE TITLE
invalid memory address or nil pointer

### ISSUE THREAD

**Issue by Aetherinox** [cooperspencer/gickup#222]
Just wanted to give you a heads up and maybe see if there's a way to solve this issue.

I updated gickup today, and it immediately failed to start. It has been running for six months without fail. 

```
2024-04-03T04:03:30Z INF Reading /gickup/conf.yml file=/gickup/conf.yml
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xd8 pc=0xc22e84]

goroutine 1 [running]:
main.readConfigFile({0xc0002189f0, 0x10})

	/go/src/github.com/cooperspencer/gickup/main.go:86 +0x564

main.main()

	/go/src/github.com/cooperspencer/gickup/main.go:629 +0xaa5

2024-04-03T04:04:14Z INF Reading /gickup/conf.yml file=/gickup/conf.yml
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xd8 pc=0xc22e84]
```

So I went searching, and luckily, I ran across this post
- https://github.com/cooperspencer/gickup/issues/117

which recommended removing the dashes at the bottom:

```
---

# you can define separate source and destination pairs,
# like "mirror all repos from github to gitea but keep gitlab repos up-to-date in ~/backup"
# if cron is defined in the first config, this cron interval will be used for all the other confgurations, except it has one of its own.
# if cron is not enabled for the first config, cron will not run for any other configuration
```

And now it works fine. Had it not been for that posted issue, would never have found that; and I think that is included in the config by default.  Definitely not something I've added.

**Comment by cooperspencer** [comment]
Thanks a lot for this issue. I'll look into this because there must be something I can do about this.

**Comment by Aetherinox** [comment]
Appreciate it. Honestly it could probably be removed and just make sure it's in the repo readme. People shouldn't be just ignoring the readme when they're trying to configure things.

Then again, I'm also a developer; and I know that people absolutely hate reading, and they'll open an issue even with the answer in front of their face.

**Comment by cooperspencer** [comment]
I think I found a fairly easy fix for that.
https://github.com/cooperspencer/gickup/pull/223

I just check if the config is `nil` and ignore it if that's the case.

This was my test configuration:
```yaml
---

source:
  github:
    - user: cooperspencer

destination:
  local:
    - path: ~/backup/
      lfs: True
      structured: True

---

---

source:
  github:
    - user: kubernetes

destination:
  local:
    - path: ~/backup
      structured: True

---
```

**Comment by Aetherinox** [comment]
Nice, that'll work great. Straight forward.

It's weird, not sure what has changed, but I've used that same config for a long time now. Gickup is pretty much a "set it and forget it" app which is nice, but after yesterday's update, that's the first time I've ever had the issue. 

Appreciate you looking into it.

**Comment by cooperspencer** [comment]
I implemented the option to add multiple configs in the same yaml file at some point. That's what caused this issue for you. Sorry for that.

**Comment by Aetherinox** [comment]
No need to be sorry, stuff happens.

Do appreciate you looking into it.

**Comment by cooperspencer** [comment]
I pushed a new release withe the fix
