### ISSUE TITLE
Publish a docker image

### ISSUE THREAD

**Issue by mikenorgate** [cooperspencer/gickup#23]
It would be really great to have this as a docker image, just makes it a bit easier to run

**Comment by cooperspencer** [comment]
That's a great idea. I will implement that.

**Comment by cooperspencer** [comment]
@sniffingsugar was so kind and created a Dockerfile before I could.
Thanks a lot :smile: 

I will add a github action to automatically build and release the Dockerfile

**Comment by mikenorgate** [comment]
Awesome, going to get this running tonight
