### ISSUE TITLE
[feature request]; support for Forgejo (fork of gitea)

### ISSUE THREAD

**Issue by ephraim-beltran** [cooperspencer/gickup#258]
The original developers of Gitea, Codeberg, have forked Gitea into Forgejo because of conflict of interest. Forgejo is completely free and has a lot of useful tools. I think it is a good addition to supported platforms as it is a good free alternative to the other Git servers.

**Comment by cooperspencer** [comment]
Forgejo is already supported; it just doesn't have a separate key in the configuration. You can use the Gitea configuration since the APIs are still the same. Once that changes, I will create a separate Forgejo module.
