### ISSUE TITLE
excludeorgs is case sensitive

### ISSUE THREAD

**Issue by mikenorgate** [cooperspencer/gickup#26]
Not a major issue but it caught me out, not sure if it's worth fixing or just making a comment somewhere.

Could possible add a dry run flag to check what it's going to do, nearly cloned many GB of organisations repos 😄

**Comment by cooperspencer** [comment]
a `--dryrun` flag sounds pretty good. I will implement that :smile:

**Comment by cooperspencer** [comment]
I just implemented a `--dryrun` flag. It will take a bit until the container is available
