### ISSUE TITLE
No fetching of bare repositories

### ISSUE THREAD

**Issue by lbdr** [cooperspencer/gickup#265]
Right now bare repositories are excluded from updates. I'm referring to the following part in the code.
https://github.com/cooperspencer/gickup/blob/fe1afa35b1b7951cfaef7b4088a2892ce05e5d49/local/local.go#L352-L375

I'd like to bare clone repositories because I don't need the working tree in the backup but I'd prefer to still receive updates as well.

Feel free to share your opinion or correct me.
Thanks!

**Comment by cooperspencer** [comment]
No need to correct you. That was a case of "verschlimmbessern".
I fixed it in this build, can you test it for me when it is done?

https://github.com/cooperspencer/gickup/actions/runs/10616620073?pr=266

And here the PR:
https://github.com/cooperspencer/gickup/pull/266/files

**Comment by lbdr** [comment]
Works! Thanks again

**Comment by cooperspencer** [comment]
I created another new release
