### ISSUE TITLE
Local update failures are silently ignored

### ISSUE THREAD

**Issue by mtoohey31** [cooperspencer/gickup#270]
I happened to notice a bunch of warnings in my gickup service logs, and upon further investigation I realized nothing had been mirroring properly for a while. To avoid this happening in the future, I was going to set up a Prometheus alert, but then I realized that there was no indication of an issue in the Prometheus metrics. I've taken a look at the source code and it looks like `local.Locally` will return `true` even when the final retry fails? To be specific, it seems to me like [this line](https://github.com/cooperspencer/gickup/blob/818c0cef4e6ee4472d11dd0bd50cb1d4072b4ffd/local/local.go#L196) should be `return false` instead of `break`. Does that sound right, or am I missing something?

**Comment by cooperspencer** [comment]
You are correct. If we change that line, it should work the way we expect it to.

**Comment by cooperspencer** [comment]
Can you test that?
https://github.com/cooperspencer/gickup/pull/271

you can download the artifact from here:
https://github.com/cooperspencer/gickup/actions/runs/10697068567

**Comment by mtoohey31** [comment]
Thanks for taking a look. I've tested it and that fixes things!

**Comment by cooperspencer** [comment]
thanks for testing. I'll merge it and push a new release.

**Comment by mtoohey31** [comment]
No problem, thank you!
