### ISSUE TITLE
Feature Request: Support for GitHub Gists 

### ISSUE THREAD

**Issue by Logicer16** [cooperspencer/gickup#273]
Great project you have here. I've already setup my config to backup all my git repos, but I would like to have the same functionality for my gists. While I could list them all manually in my config, ideally gickup would be able to do this for me.

This would be done similarly to the current GitHub implementation, using different [endpoints](https://docs.github.com/en/rest/gists/gists?apiVersion=2022-11-28) to list a user's gists, and then obtaining the gist's git remote url and comments.

**Comment by cooperspencer** [comment]
sounds great, I'll look into it.

**Comment by cooperspencer** [comment]
I implemented the feature. You can download a test-version from this build:
https://github.com/cooperspencer/gickup/actions/runs/11083110915

You just add `gists: true` to your github configuration.

**Comment by Logicer16** [comment]
Wow, that was quick. Incredible.

Tried it out and it works as expected. Thanks for your help.

**Comment by Logicer16** [comment]
Fixed in #274
