### ISSUE TITLE
ERROR: [stat /tmp: no such file or directory]

### ISSUE THREAD

**Issue by MRTharani** [cooperspencer/gickup#275]
ERR stat /tmp: no such file or directory stage=tempclone url=https://github.com/Tetrax-10/reddit-backup-restore.git
i tried to backup to s3

**Comment by cooperspencer** [comment]
I have a few questions beforehand:

- What system are you running it on?
- Are you using docker?
- If docker, which container are you using?

**Comment by MRTharani** [comment]
Thanks for replying,
I am using Docker on Ubuntu latest,
I Got Work Around for the Issue.
While Gickup uses only S3 for backup,I don't have any access to S3 nor knowledge about S3, so I used Gickup to backup locally and used rclone to transfer to Any Cloud I want to with encryption...

Feature Request:
I am one of the person who needs gist backup as well...

**Comment by cooperspencer** [comment]
You can already try the gist feature if you want.
https://github.com/cooperspencer/gickup/actions/runs/11083110915
You can download the latest build and just add `gists: true` to your github source configuration.

**Comment by MRTharani** [comment]
Thanks i will try as soon as possible

**Comment by MRTharani** [comment]
> You can already try the gist feature if you want. https://github.com/cooperspencer/gickup/actions/runs/11083110915 You can download the latest build and just add `gists: true` to your github source configuration.

How I can use this build in docker.

**Comment by cooperspencer** [comment]
you can use this container: buddyspencer/gickup:ubuntu-dev

**Comment by MRTharani** [comment]
> you can use this container: buddyspencer/gickup:ubuntu-dev

thanks i will give it a try

**Comment by william6847** [comment]
i get the same
`ERR stat /tmp: no such file or directory stage=tempclone url=my-gitlab`
error trying to copy from gitlab to github and couldn't find any information about the tmp folder the message is talking about or if i messed up the access rights.
It is able to detect all my repositories but prints this error for every repo its trying to copy

**Comment by cooperspencer** [comment]
Hi,
What system are you using? If you try to mirror repos from gitlab to github, gickup will clone the repo into /tmp, push it to the mirror location and remove it from /tmp afterwards.

**Comment by william6847** [comment]
Hey, I run a vm with
x86_64 debian stable with kernel version 6.1.124

**Comment by cooperspencer** [comment]
ok, thanks. I will have a look at it and try to reproduce the issue.

**Comment by cooperspencer** [comment]
I just ran a mirror from github to gitlab and it worked fine. Can you share your config with me?

**Comment by william6847** [comment]
Docker-compose.yml :
version: "3"
services:
  runner:
    # build: . # If you want to Build the Image locally (You need the complete Repo on your PC)
    image: buddyspencer/gickup:latest
    volumes:
      - ${PWD}/conf.yml:/gickup/conf.yml # Change the path of your local config ${PWD} is your current directory (where the docker-compose.yml is located)
    command: ["/gickup/conf.yml"] # Changes the path of the internal bound config
    # Uncomment these 2 lines and set timezone appropriately to specify cron in local time instead of UTC.
    # environment:
    #   - TZ=America/Los_Angeles

conf.yml :
source:
  gitlab:
    - token:
      url: https://*******.com
      username: user
      ssh: true
      sshkey:

destination:
  github:
    - token:  // token has api scope
      force: true
      visibility:
        repositories: private


Output logs:
WARN[0000] /home/william/docker/compose/gickup/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
[+] Running 1/1
 ✔ Container gickup-runner-1  Created                                                                         0.0s
Attaching to runner-1
runner-1  | 2025-01-29T11:39:28Z INF Reading /gickup/conf.yml file=/gickup/conf.yml
runner-1  | 2025-01-29 11:39:28 INF Configuration loaded destinations=1 pairs=1 sources=1
runner-1  | 2025-01-29 11:39:28 INF Backup run starting
runner-1  | 2025-01-29 11:39:29 INF grabbing repositories from user stage=gitlab url=https://*******.com
runner-1  | 2025-01-29 11:39:32 INF starting backup for https://*******.com/project/local-server.git stage=backup
runner-1  | 2025-01-29 11:39:32 INF mirroring local-server to https://github.com stage=github url=https://github.com
runner-1  | 2025-01-29 11:39:32 ERR stat /tmp: no such file or directory stage=tempclone url=https://*******.com/project/local-server.git
runner-1  | 2025-01-29 11:39:32 INF starting backup for https://*******.com/project/ext-server.git stage=backup
runner-1  | 2025-01-29 11:39:32 INF mirroring ext-server to https://github.com stage=github url=https://github.com
runner-1  | 2025-01-29 11:39:32 ERR stat /tmp: no such file or directory stage=tempclone url=https://*******.com/project/ext-server.git
runner-1  | 2025-01-29 11:39:32 INF starting backup for https://*******.com/project/v1-server.git stage=backup
runner-1  | 2025-01-29 11:39:32 INF mirroring v1-server to https://github.com stage=github url=https://github.com
runner-1  | 2025-01-29 11:39:32 ERR stat /tmp: no such file or directory stage=tempclone url=https://*******.com/project/v1-server.git
runner-1  | 2025-01-29 11:39:32 INF Backup run complete duration=3.77102001s
runner-1 exited with code 0

**Comment by cooperspencer** [comment]
I think I found your problem. The current `latest` still uses scratch as a base for the container.
As seen here: https://github.com/cooperspencer/gickup/blob/v0.10.36/Dockerfile#L18

With the next release, it will use alpine as the new base so that should fix that specific problem.
As seen here: https://github.com/cooperspencer/gickup/blob/main/Dockerfile#L18

But as to fixing your current problem, you can change from `latest` to `ubuntu-latest` and then it should be fine.
