### ISSUE TITLE
Dockerfile missing git-lfs package?

### ISSUE THREAD

**Issue by awbn** [cooperspencer/gickup#278]
Running the default image `buddyspencer/gickup:latest`  with `lfs: true` for a local destination in the config file results in the following error:

```
2024-10-23T00:10:26-07:00 INF starting backup for https://github.com/cooperspencer/gickup.git stage=backup
2024-10-23T00:10:26-07:00 ERR git lfs is not installed path=/data stage=locally
2024-10-23T00:10:26-07:00 INF cloning github.com/cooperspencer/gickup.git/1729667426 path=/data stage=locally
2024-10-23T00:10:26-07:00 WRN retry 1 from 5 error="exec: no command" path=/data stage=locally
``` 
(retries unsuccessfully before eventually failing)

Using the `:ubuntu-latest` image or removing `lfs: true` from the config file does allow the backup to succeed.

#204 added the `git-lfs` package to `Dockerfile.ubuntu` but not to the base `Dockerfile` used for the `:latest` image. Given that  `lfs` is a documented config option, can be added in the default image?

**Comment by cooperspencer** [comment]
Hi,
Not sure if that solves your issue, because the part, in which you added git-lfs, is only the builder. The part, where gickup is executed, is from scratch and neither `git` nor `git-lfs` are copied over there.

**Comment by awbn** [comment]
Ah, of course it doesn't. That's what I get for proposing a quick fix without testing it :)

I see that the code is shelling out to the external git binary when running with lfs. Given that dependency (and since `go-git` doesn't support lfs), have you considered using alpine with git/git-lfs as the base image for the container rather than scratch? It's only marginally larger than the scratch-based version and gives more flexibility (and is still < 1/3 of the size of the Ubuntu version)
