### ISSUE TITLE
Feature request - Add functionality for Bitbucket.

### ISSUE THREAD

**Issue by blofeldthefish** [cooperspencer/gickup#3]
Hi there,

Thank you for this useful tool, it proving to be a boon for centralising several disparate repositories into one spot.

I was wondering if there are plans to add support for Bitbucket (Server and/or Cloud) into the scope of available services to connect/interact with ?

Thanks again.

**Comment by cooperspencer** [comment]
Hi,
That wasn't in my original scope, but I will try to add it.

**Comment by cooperspencer** [comment]
I just pushed a new branch for bitbucket. You should be able to get repos from there and mirror them to everywhere else.

**Comment by cooperspencer** [comment]
I just merged the bitbucket branch into the master
