### ISSUE TITLE
gickup Mirror issue

### ISSUE THREAD

**Issue by JManDoo** [cooperspencer/gickup#31]
Gickup mirrors my Github repos to my local Gitea for the first pull, but any commits I have after, Gickup doesnt mirror the changes

I delete the local Gitea Repos and then run Gickup and it will mirror them again.  Is this your expectation or is it possible there is either a bug in the Gitea API since the mirror: true is already set, or something in gickup api call?

**Comment by cooperspencer** [comment]
Hi,
I will have a look at it. Maybe there's a problem with the pull interval, I might need to implement a pull interval in the config or see if I can tell gitea to force pull per api call. I'll come back to you, when I know more.

**Comment by cooperspencer** [comment]
Pushed a new release with the fixes.

**Comment by JManDoo** [comment]
Excellent! it works as I would expect now! Thank you for your quick response

**Comment by cooperspencer** [comment]
You are welcome 😁

**Comment by JManDoo** [comment]
Sorry to bug you, but I have another question, If I delete a file from a github repo and then run gickup, should it then purge the file from my local gitea repo?  It would appear that modifying files do sync the changes after your latest change, but if I delete a file from the source location, it does not purge it from the destination.

**Comment by cooperspencer** [comment]
No problem :smile: 
This seems to be a Gitea issue. I just tell Gitea per API call to resync with the source repo.

**Comment by JManDoo** [comment]
<img width="477" alt="image" src="https://user-images.githubusercontent.com/21066923/145727271-9e5406a5-c1a8-409e-ab05-ac0363a2635b.png">

Thank you again
