### ISSUE TITLE
gitea self hosted destination

### ISSUE THREAD

**Issue by dyslexicjedi** [cooperspencer/gickup#35]
I'm getting the following error when trying to use my internal self-hosted gitea instance as a destination.

`
1:21AM PNC Get "gitea.dyslexicjedi.com/api/v1/version": unsupported protocol scheme "" stage=gitea url=gitea.dyslexicjedi.com
panic: Get "gitea.dyslexicjedi.com/api/v1/version": unsupported protocol scheme ""

goroutine 1 [running]:
github.com/rs/zerolog.(*Logger).Panic.func1({0x207c1e0, 0x4b})
	/home/runner/go/pkg/mod/github.com/rs/zerolog@v1.26.0/log.go:359 +0x38
github.com/rs/zerolog.(*Event).msg(0x205a090, {0x207c1e0, 0x4b})
	/home/runner/go/pkg/mod/github.com/rs/zerolog@v1.26.0/event.go:149 +0x324
github.com/rs/zerolog.(*Event).Msg(...)
	/home/runner/go/pkg/mod/github.com/rs/zerolog@v1.26.0/event.go:108
main.BackupGitea({{0x2250b60, 0x9}, {0x22cf9e0, 0x2d}, {0x22cf9b0, 0x29}, {0x201f530, 0x28}, {0x2250c00, 0x4}, ...}, ...)
	/home/runner/work/gickup/gickup/main.go:267 +0x288
main.Backup({0x2518000, 0x1, 0x1}, 0x2108400)
	/home/runner/work/gickup/gickup/main.go:393 +0x368
main.main()
	/home/runner/work/gickup/gickup/main.go:645 +0x4c0
`

**Comment by dyslexicjedi** [comment]
When I hit gitea.dyslexicjedi.com/api/v1/version with a web browser manually, I get the following response.

{"version":"1.15.7"}

**Comment by cooperspencer** [comment]
Hi,
can you add https:// or http:// in front of your URL? I don't add the protocol to the url in the code.

**Comment by dyslexicjedi** [comment]
I feel like an idiot, problem is definitely between the seat and keyboard.
