### ISSUE TITLE
Allow includes in addition to excludes

### ISSUE THREAD

**Issue by colindean** [cooperspencer/gickup#37]
I'd love to specify a list of repos that should be allowed. I create A LOT of forks and don't need to back them up. I'd rather risk forgetting something because it's not on an `include` list than pull down a bajillion repos I don't care to back up.

**Comment by cooperspencer** [comment]
that sounds plausible :smile: 
I'll have a look at that

**Comment by cooperspencer** [comment]
I added the include option. the new release should be available in the next minutes
