### ISSUE TITLE
Gitlab Groups

### ISSUE THREAD

**Issue by wkelton** [cooperspencer/gickup#40]
For Gitlab, it appears that repos from all groups (as member / owner) are not being backed up. Only the repos from one of my groups are being pulled.

Is this a configuration issue on my side, or something missing?

**Comment by cooperspencer** [comment]
Gitlab is not completely fine by now. I have to put a little bit more research into gitlab.

**Comment by cooperspencer** [comment]
that should be fixed in the main branch. Can you test if it works for you?

**Comment by wkelton** [comment]
Fixed for me. Fast work!

**Comment by cooperspencer** [comment]
glad to hear 😄
