### ISSUE TITLE
Some more documentation of the config options

### ISSUE THREAD

**Issue by pschichtel** [cooperspencer/gickup#41]
I like that you provide a example config which seems to be pretty complete, however I think it would be useful to have a few comments in there explaining what values should go where (e.g. was is the difference between user and username?), which fields are optional (e.g. the entire logging section) and similar stuff like that.

**Comment by cooperspencer** [comment]
Hi,
I will add more documentation to the example config.

**Comment by cooperspencer** [comment]
[new documentation](https://github.com/cooperspencer/gickup/blob/additional_documentation/config.example.yml)

**Comment by pschichtel** [comment]
that confirms a few assumptions I had, thanks! Can be closed unless you have some more documentation planned.
