### ISSUE TITLE
Reload configuration file on changes

### ISSUE THREAD

**Issue by colindean** [cooperspencer/gickup#48]
In my setup, I've got my configuration file mounted via NFS inside of a container. That configuration file resides on my NAS. I'd love not to have to restart the container when I change the configuration file when running in scheduled mode. 

https://github.com/fsnotify/fsnotify seems like it would handle this for local filesystems, but its README explains:

> fsnotify requires support from underlying OS to work. The current NFS protocol does not provide network level support for file notifications.

So that won't address my particular use case.

**Comment by cooperspencer** [comment]
But we could calculate a checksum of the configfile and run that check every once in a while to see if it has changed. If it has changed, we can do a reload of the configuration.

**Comment by RyanBalfanz** [comment]
Going to drop this here as well to spur additional discussion: https://ieftimov.com/post/four-steps-daemonize-your-golang-programs/#reload-config-on-sighup

**Comment by cooperspencer** [comment]
I implemented a configuration reload. Initially, I used fsnotify, but then I recalled this issue. The configuration is now reloaded every 5 seconds, and it's compared with the currently loaded one. If there's a difference, the new configuration is applied.
