### ISSUE TITLE
Gitlab clones repos from teams in orgs into $team/$repo instead of $org/$team/$repo

### ISSUE THREAD

**Issue by colindean** [cooperspencer/gickup#49]
I have a gitlab org that has several teams that have repos under them. When gickup backs up those repos, it places them in an unexpected place:

Gickup logs:

```
2021-12-17 17:16:15 INF starting backup for https://gitlab.com/codeandsupply/survey-team/comp-survey-2020-results.git stage=backup
2021-12-17 17:16:15 INF cloning gitlab.com/survey-team/comp-survey-2020-results path=/gickup/data/backups stage=locally
```

On disk:

```
[/share/Container/Gickup] # ls  backups/gitlab.com/survey-team/
2017 Compensation Survey Analysis/  comp-survey-2020-results/
```

I would expect gickup to maintain the `$org/$team/$repo` structure when backing up from teams' repos.

**Comment by cooperspencer** [comment]
I just uploaded a fix for that into the `main` branch with 9606d07. Can you test if it is meets your expectations.

**Comment by colindean** [comment]
It does! Thank you!

**Comment by colindean** [comment]
...it's pretty safe for me to delete the gitlab backup directory entirely and just let Gickup redownload it with the correct file structure, right? I don't see anything that would preclude such.

**Comment by cooperspencer** [comment]
It should be ok to do so
