### ISSUE TITLE
Enabling observability with metrics pushed

### ISSUE THREAD

**Issue by colindean** [cooperspencer/gickup#50]
I've got some dashboards and alerts set up for my home lab. Now that I've got gickup running regularly, I'd like to be able to push some statistics to Influx from gickup. Adding this to gickup itself will add some complexity so I want to see what others think before I grab some [glögg](https://en.wikipedia.org/wiki/Gl%C3%B6gg) and have at it. 

I thought about Prometheus but I think the current architecture of gickup lends itself to push metrics rather than pull. TBH I've only used either Influx or Prom in recent history and they're setup in my home lab infra so I have a preference for those and only those.

**Comment by colindean** [comment]
Metrics I think I'd want to know:

* Count of repos found on discovery
* Count of repos freshly cloned
* Count of repos with a clone error
* Count of repos successfully pulled
* Count of repos with a pull error
* Speed of clones
* Speed of pull, e.g. how long did it take to `git pull` a repo to ensure that it's up to date
* Count of repos backed up
* Byte size of backup (not sure if this should be gickup's responsibility to report... might be a job for another program?)

**Comment by colindean** [comment]
https://docs.influxdata.com/influxdb/v2.1/api-guide/client-libraries/go/ seems to indicate that we'd need to import `"github.com/influxdata/influxdb-client-go/v2"` and use the `bucket`, `org`, `token`, and `url` supplied by the user in a config file...

```go
func main() {
    bucket := "example-bucket"
    org := "example-org"
    token := "example-token"
    // Store the URL of your InfluxDB instance
    url := "http://localhost:8086"
    // Create new client with default option for server url authenticate by token
    client := influxdb2.NewClient(url, token)
    // User blocking write client for writes to desired bucket
    writeAPI := client.WriteAPIBlocking(org, bucket)
    // Create point using full params constructor
    p := influxdb2.NewPoint("stat",
        map[string]string{"unit": "temperature"},
        map[string]interface{}{"avg": 24.5, "max": 45},
        time.Now())
    // Write point immediately
    writeAPI.WritePoint(context.Background(), p)
    // Ensures background processes finishes
    client.Close()
}
```

Setting up the infra to send seems pretty easy but wiring it up may not prove so easy since we'll need to pass it around or have a singleton with a configured client/api instance.

**Comment by colindean** [comment]
Singleton wrapper for the influx client: https://refactoring.guru/design-patterns/singleton/go/example

(N.b. I'm basically dropping notes here for myself, or whoever may pick this up before me!)

**Comment by cooperspencer** [comment]
I use prometheus at work and also had to write a few exporters in my time, so I would naturally prefer the Prometheus way tbh.

**Comment by colindean** [comment]
Prom integration looks a lot easier because of a healthy abstraction OOTB, so I'll head in that direction: https://prometheus.io/docs/guides/go-application/

I did start a little on influx so maybe after Prom, I'll continue with Influx...?

**Comment by cooperspencer** [comment]
The more the merrier

**Comment by colindean** [comment]
I switched to focusing on the Prom impl. It's a lot easier and cleaner and surfacing a better pattern for a generic counter that would send to both Prom and Influx plus any other future metrics system.

I think I'm going to rip out the Influx stuff for now... it's messy.

**Comment by colindean** [comment]
https://github.com/cooperspencer/gickup/compare/main...colindean:metrics
