### ISSUE TITLE
GitLab project name is used in place of repository name

### ISSUE THREAD

**Issue by Enrico204** [cooperspencer/gickup#54]
When backing up from GitLab, the project name is used instead of the repository name.

For example, [this repository](https://gitlab.com/Enrico204/dd-wrt-prometheus-exporter) is created using the name `DD-WRT Prometheus Exporter` instead of `dd-wrt-prometheus-exporter`, which is the expected behavior (also the safer one).

**Comment by cooperspencer** [comment]
I replaced `r.Name` with `r.Path` for gitlab, now it clones the repos in the expected behavior.
the change is already in the newest commit in main.

**Comment by Enrico204** [comment]
Thanks! I verified with the latest `main` and it's working as expected :-)
