### ISSUE TITLE
Github clone with read-only repo access?

### ISSUE THREAD

**Issue by dbr** [cooperspencer/gickup#56]
Is there a way to give gickup access to private Github repos **in read-only** mode?

The might well be a limitation of Github,

1. If you just add a second SSH key, it'll obviously have read/write access via `git clone` and `git push` etc. The key listing says "read/write" but there's no obvious option to create a new key as "read only".
2. If you create an access token without the full `repo` scope (i.e nothing checked), it only has access to public repos (which can be done without a token anyway)
3. With the full `repo` scope, HTTPS-clone with token as password has full read/write access to all repos. ["HTTPS cloning with OAuth tokens"](https://docs.github.com/en/developers/overview/managing-deploy-keys#https-cloning-with-oauth-tokens) implies there is a way to have more fine-grained control over permissions like this, but I couldn't find it
4. There is a "deployment key" which can be read-only but that needs to be added per-repo
5. There is ["machine users"](https://docs.github.com/en/developers/overview/managing-deploy-keys#machine-users) but "Only organizations can restrict machine users to read-only access. Personal repositories always grant collaborators read/write access", and would need added per-repo also I think

**Comment by cooperspencer** [comment]
I don't think there is an easy way. I don't see a way to get the private repos without the token that has full permissions over repositories...

**Comment by jakubdyszkiewicz** [comment]
That's disappointing :(

But even if Github provides a way to restrict the token for only reading repos, I _think_ the token is scoped for all repos! If you use the same account for work, you need to be extremely careful with the token. For me, that's a non-starter.

Luckily, `gickup` works with public repos without auth. I try to keep all repos public, my old private repos are on gitlab anyways.

**Comment by colindean** [comment]
[This SO post](https://stackoverflow.com/a/65504563/204052) seems to indicate that a deploy key is a way to handle read-only access, but it's SSH only. I don't think there's another way to accomplish this. [This SO question](https://stackoverflow.com/q/42652815/204052) has more explanations.

**Comment by dbr** [comment]
A solution to this this seems to be on Github's roadmap:

https://github.com/github/roadmap/issues/184

> However, PATs only have broad scopes (e.g. repos or orgs), which grant access to anything the user can access (i.e. specific repos or orgs cannot be specified). This improvement will introduce a new version of PATs which provide users with the ability to scope access to specific repos and orgs, set fine-grained permissions across specific features, and set expiration dates for each token

**Comment by dbr** [comment]
This is now possible,
https://github.blog/2022-10-18-introducing-fine-grained-personal-access-tokens-for-github/
A token with read only access to repository content seems to do what I was hoping - closing!
