### ISSUE TITLE
Bitbucket error

### ISSUE THREAD

**Issue by Tassleh0ff** [cooperspencer/gickup#66]
Hi, I have some issues with Bitbucket, basically I'm trying to backup some repos using a yaml file like this
```
source:
  bitbucket:
    - user: mycompany
      username: myusername
      password: mypassword
      ssh: false
      sshkey: /root/.ssh/id_rsa
      include:
        - myproject1
        - myproject2
destination:
  local:
    - path: /opt/backup/bitbucket
      structured: true         

log: 
  timeformat: 2006-01-02 15:04:05
  file-logging:
    dir: /var/log/gickup
    file: gickup.log       
    maxage: 180      
```

In this case the user value is my company username where there are all the repositories (https://bitbucket.org/mycompany/myproject1, https://bitbucket.org/mycompany/myproject2, etc etc...).
Please note that destination and log directories exist and the user I'm using have write permissions.

If I try it gickup returns me these errors
```
[root@vault ~]#gickup gickup.yml
2021-12-23T11:25:12+01:00 INF Reading gickup.yml file=gickup.yml
2021-12-23 11:25:12 INF grabbing repositories from mycompany stage=bitbucket url=https://api.bitbucket.org/2.0
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
gickup/bitbucket.Get(0xeb33b0)
        /home/runner/work/gickup/gickup/bitbucket/bitbucket.go:36 +0xe59
main.RunBackup(0xc0001a0640)
        /home/runner/work/gickup/gickup/main.go:135 +0xa5
main.main()
        /home/runner/work/gickup/gickup/main.go:175 +0x71f
```
I'm using a CentOS 7 vm (with latest updates), selinux in permissive mode and gickup 0.9.8-2.
The vm doesn't have any restrictions on outbound network traffic.

Do you think there are some requirements I'm missing?
Are there some debug parameters I can use to get more informations on this error?

Thank you

Tas

**Comment by cooperspencer** [comment]
Hi,
in line 36 are a few interface to string conversions happening. I guess it happens because user doesn't return proper value.
Can you compile this branch and try if it works for you? https://github.com/cooperspencer/gickup/tree/bitbucket_nil

**Comment by Tassleh0ff** [comment]
Works perfectly, thank you!
