### ISSUE TITLE
panic: x509: decryption password incorrect

### ISSUE THREAD

**Issue by nachtschatt3n** [cooperspencer/gickup#71]
Hi there, thank you for the great tool! 

I tried to backup my bitbucket to my local machine and have a very simple config like this: 

`source:`
`  bitbucket:`
`    - user: myorg `
`      username: my@user.de `
`      ssh: true `
`      sshkey: /Users/myuser/.ssh/id_rsa`

But I get a "panic: x509: decryption password incorrect". There are no passwords :) My user is also managed by google therefore I do not have an extra user with bitbucket it's my google user. 

Any Idea what I'm doing wrong?

**Comment by cooperspencer** [comment]
Hi,
thanks, glad you like it 😄 
You can create an app password for gickup.
It's located in `Access Management` in `Personal Setting`.

**Comment by nachtschatt3n** [comment]
I did and now its:
`2021-12-28 12:53:32 FTL 401 Unauthorized stage=bitbucket url=https://api.bitbucket.org/2.0`

I have now **user** with the org, **username** with my user name, and **password**  with the app password.

**Comment by cooperspencer** [comment]
I just created an organization on bitbucket to test it. I created my app password with the following options:
![image](https://user-images.githubusercontent.com/27288824/147564871-32e54bbe-078d-4d02-8076-d967fbcf8440.png)

it works fine for me. With which options did you create your password?

**Comment by nachtschatt3n** [comment]
Well... I gave it all the rights. But I just recreated the app password with just projects and repo read. 

' FTL 401 Unauthorized stage=bitbucket url=https://api.bitbucket.org/2.0'

I now removed all the settings therefore I only have the user, username, password, and the destination section. I'm certainly missing something here. The project read seems to work cos the line before the 401 is: 

'2021-12-28 13:15:18 INF grabbing repositories from ibdigital stage=bitbucket url=https://api.bitbucket.org/2.0'

**Comment by cooperspencer** [comment]
can you share the whole output with me? If you feel uneasy posting it here, you can also send it to me per mail.

**Comment by nachtschatt3n** [comment]
well I guess there are no real secrets in there. I did a little video https://www.youtube.com/watch?v=a0m8FJ9ZKLg

**Comment by cooperspencer** [comment]
can you try `mathias_uhl` as `username`?

**Comment by nachtschatt3n** [comment]
incredible! Thank you that did the trick.

**Comment by cooperspencer** [comment]
Thanks for upload such a high quality video 😄 
So I could read the your username
