### ISSUE TITLE
version is unkown

### ISSUE THREAD

**Issue by gremi-jr** [cooperspencer/gickup#75]
Hi, 

is there a reason why version is set to unkown? It suprised me a little bit after I updated to the newest version. 
After I adjusted the variable to the appropriate version based on the release, it seems to work just fine.

PS: I use the binary version.

**Comment by cooperspencer** [comment]
Hi,
I use goreleaser to build the release binary and that overwrites the version variable. If you build it on your own or download it from the actions it says `unknown`. 
If you want to set your own version use this to build it `go build -ldflags '-X "main.version=0.9.9"'`

**Comment by gremi-jr** [comment]
Alright, now it makes sense to me. Thank you for clarification! Then I will use the binary from the release.
