### ISSUE TITLE
Docker Compose and Docker conf file inconsistency

### ISSUE THREAD

**Issue by VxJasonxV** [cooperspencer/gickup#83]
The current release of gickup on DockerHub ( https://hub.docker.com/layers/buddyspencer/gickup/0.9.9-1/images/sha256-e68b7d48f604949b8bc171fe7cc572ff184249443b7a64fcc6a28918400903cd?context=explore ) does not include a command parameter for where to look for the configuration file, so instead of looking for it at `/gickup/conf.yml` as the Docker Compose file references, it has to be mounted at `/conf.yml` instead.

![Screenshot of 'Volume' options for Docker container on Synology DSM7](https://user-images.githubusercontent.com/1882/148307049-e7578b16-898b-4203-acc7-10a39c715a19.png)

This screenshot is the Volume management section of Docker container configuration on a Synology NAS, though I had similar issues running it directly via `docker build` (not Compose, naturally).

This may be my inexperience with Compose vs "classic" (single container?) deployments, but the inconsistency with each other and documentation threw me for a loop. Perhaps also misunderstanding the purpose of using Compose vs classic deployments as a relatively new Docker user.

**Comment by cooperspencer** [comment]
If you want a different config name or path, you can run gickup like this
```bash
docker run -ti -v /path/to/conf.yml:/config.yml buddyspencer/gickup gickup/app config.yml
```

**Comment by VxJasonxV** [comment]
I'm not asking how to change the config file path, I'm pointing out the inconsistency between `Dockerfile` and `docker-compose.yml`:

```
    image: buddyspencer/gickup:latest
    volumes:
      - ${PWD}/conf.yml:/gickup/conf.yml
    command: ["./gickup/app", "/gickup/conf.yml"]
```
```
WORKDIR /
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /go/src/github.com/cooperspencer/gickup/app /gickup/app
COPY --from=builder /usr/share/zoneinfo /usr/share/zoneinfo
CMD ["./gickup/app"]
```

The running command discrepancy. This also assumes that both container files are expected to be used for the same purpose.

**Comment by sniffingsugar** [comment]
@VxJasonxV ahh I see what you are up to.

The command in the compose file with overwrite the Dockerfile CMD.
Maybe I should have used ENTRYPOINT so that such questions don't arise.

I will create an PR that will "solve" that Issue. :)
