### ISSUE TITLE
Docker image permission error

### ISSUE THREAD

**Issue by DavidGL17** [cooperspencer/gickup#87]
Hi,

i have been trying to setup your app as a docker container on my system, and have run into a few issues with the docker image. Basically, when pulling the image from docker hub the docker-compose up will fail and give this error message : 

```
Cannot start service gickup: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/conf.yml": permission denied: unknown
```

I tried debugging for a while and ran into a lot of posts saying that it may be an issue with the permissions of the executable inside of the docker image (it does not have the right permissions to be executed from the docker image).

I tried building the image from scratch on my end and it worked, so I'm guessing the issue causing this was fixed in the repository since the image was uploaded to docker hub. I think the image needs to be updated accordingly to fix this issue.

**Comment by cooperspencer** [comment]
Hi,
yes you are right. We changes the Dockerfile in one of the last commits. That causes the issue, that you experience. I will push a new release today and then it should be fine again.

**Comment by DavidGL17** [comment]
Perfect thank you very much!

**Comment by cooperspencer** [comment]
I created a new release and uploaded a new container. For me it is working now. I'll close it for now. If you have any troubles just reopen it.

**Comment by DavidGL17** [comment]
Sry, meant to update you and forgot : yes thank you i saw, i tested and all is working now thank you!
