### ISSUE TITLE
Invalid header with token_file option

### ISSUE THREAD

**Issue by amaldonado-hcg** [cooperspencer/gickup#94]
Hi there! I'm trying to use the `token_file` option in the configuration file, but I got this error:

```
FTL Get "https://api.github.com/user": net/http: invalid header field value "Bearer xyz_token\n" for key Authorization stage=github url=https://github.com
```
but the same `xyz_token` works fine on the `token` option. Am I missing something here?

version 0.10.1, btw.

**Comment by cooperspencer** [comment]
Hi,
I just tried it in my configuration and I get this error message when I have a new line in my token-file. Just remove the second line and it should be fine.

**Comment by cooperspencer** [comment]
in the next release that shouldn't happen anymore, just implemented a removal for new line characters.

**Comment by amaldonado-hcg** [comment]
I see the expected behavior now, thanks!
