### ISSUE TITLE
Bitbucket authentication

### ISSUE THREAD

**Issue by drewmoseley** [cooperspencer/gickup#95]
I'm unable to get bitbucket syncing working.  With the following in my conf.yml
`  bitbucket:
    - user: drewmoseley
      username: drewmoseley
      password: REDACTED
      ssh: true
      sshkey: /.ssh/id_rsa_dmoseley_github_home
`
using an app-specific password with repo read permissions, gickup never seems to get past the "grabbing repositories" step.  Interestingly if I download the `go-bitbucket` library manually and attempt to run the `tests/list_test.go` file with the same app-specific password, it has a similar apparent lockup.

Does anyone know if user and username are the same thing?

Thanks
Drew

**Comment by cooperspencer** [comment]
Regarding `username` and `user` they aren't the same. It is explained in the example configuration. `user` is the user that you want to clone the repositories from, `username` is used for the authentication to clone said repositories.

After I read your question, I had a closer look at my bitbucket implementation and realized that I could set the value for `user` to `username` if it is empty. That solves this issue

**Comment by drewmoseley** [comment]
Strange. It still does not work in my case. It seems that the authentication step never completes.  I'm discussing it[ over here](https://github.com/ktrysmt/go-bitbucket/issues/184).

**Comment by cooperspencer** [comment]
did you pull the latest changes?

**Comment by drewmoseley** [comment]
Yes. I tried it with user set and with it clear and had the same behavior.

**Comment by drewmoseley** [comment]
Strange. I created a new bitbucket account and I can get it to work with that one.  No idea what is different about my primary account.

**Comment by cooperspencer** [comment]
that's weird, but in that case I don't think it is a gickup issue.

**Comment by drewmoseley** [comment]
Agreed.  I'll post here if I find out anything in case others have a similar issue.

**Comment by cooperspencer** [comment]
thank you

**Comment by drewmoseley** [comment]
FWIW, there is a bug in the go-bitbucket library that caused this.  The fix was recently merged so when a new release makes its way into the package stream, this should start working.

**Comment by armond1978** [comment]
Is there any ETA on the next release which is going to include this fix (updated go-bitbucket library)?

**Comment by cooperspencer** [comment]
I would like to implement Gitbucket first and then I would push a new release. If this is urgent for you, please try the master branch, the updated module should be already in there.

**Comment by cooperspencer** [comment]
@armond1978 I just published a new release. Could you please try if everything works for you?

**Comment by drewmoseley** [comment]
FWIW, I finally got back to this and it seems to work for me.  Thanks a lot.

**Comment by cooperspencer** [comment]
Glad it works for you

**Comment by armond1978** [comment]
@cooperspencer Sorry for replying with delay. But I just want to confirm that the updated version is working for me. Thanks a lot for taking care of this issue.
